//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderdetail
    {
        public int oId { get; set; }
        public int cId { get; set; }
        public int orderno { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
